SELECT /* _SQL_ID_ */
	USERS.ID,
	USERS.USER,
	USERS.PASSWORD,
	USERS.FIRST_NAME,
	USERS.LAST_NAME,
	USERS.LOCK_VERSION,
	USERS.CREATED_AT,
	USERS.UPDATED_AT,
	USERS.DELETED_AT,
	USERS.CREATOR_ID,
	USERS.UPDATER_ID,
	USERS.DELETER_ID
FROM
	USERS
WHERE
	USERS.USER = /*user*/''

