SELECT /* _SQL_ID_ */
	OWNERS.ID
,	OWNERS.FIRST_NAME
,	OWNERS.LAST_NAME
,	OWNERS.ADDRESS
,	OWNERS.CITY
,	OWNERS.TELEPHONE
,	GROUP_CONCAT(PETS.NAME)		AS	PETS_NAME
FROM
	OWNERS
LEFT OUTER JOIN
	PETS
ON
	OWNERS.ID	=	PETS.OWNER_ID
/*BEGIN*/
WHERE
/*IF SF.isNotEmpty(lastName) */
	LAST_NAME		LIKE	'%'	||	/*lastName*/''	||	'%'
/*END*/
/*END*/
GROUP BY OWNERS.ID
ORDER BY OWNERS.ID
