SELECT /* _SQL_ID_ */
	PETS.ID
,	PETS.NAME
,	PETS.BIRTH_DATE
,	PETS.TYPE_ID
,	PETS.OWNER_ID
,	TYPES.NAME AS TYPE_NAME
FROM
	PETS
LEFT OUTER JOIN
	TYPES
ON
	PETS.TYPE_ID	=	TYPES.ID
WHERE
	PETS.OWNER_ID	=	/*ownerId*/3