SELECT /* _SQL_ID_ */
	SPECIALTIES.ID
,	SPECIALTIES.NAME
FROM
	VETS
INNER JOIN
	VET_SPECIALTIES
ON
	VETS.ID	=	VET_SPECIALTIES.VET_ID
INNER JOIN
	SPECIALTIES
ON
	VET_SPECIALTIES.SPECIALTY_ID	=	SPECIALTIES.ID
WHERE
	VETS.ID	=	/*id*/3
ORDER BY
	VETS.ID