SELECT /* _SQL_ID_ */
	VETS.ID
,	VETS.FIRST_NAME
,	VETS.LAST_NAME
,	GROUP_CONCAT(SPECIALTIES.NAME)	AS	SPECIALTIES_NAME
FROM
	VETS
LEFT OUTER JOIN
	VET_SPECIALTIES
ON
	VETS.ID	=	VET_SPECIALTIES.VET_ID
LEFT OUTER JOIN
	SPECIALTIES
ON
	VET_SPECIALTIES.SPECIALTY_ID	=	SPECIALTIES.ID
GROUP BY
	VETS.ID
ORDER BY
	VETS.ID